export const mockPosts = [
  {
    id: '1',
    profilePic: 'https://i.pravatar.cc/150?img=10',
    fullName: 'Liam Parker',
    username: 'liamparker',
    postDate: '1h ago',
    postText: 'Excited to launch my new project! 🚀',
    postContent: 'https://placekitten.com/600/400', // Example image
    messageCount: 15,
    repostCount: 8,
    heartCount: 30,
    viewsCount: 200,
  },
  {
    id: '2',
    profilePic: 'https://i.pravatar.cc/150?img=2',
    fullName: 'Jane Smith',
    username: 'janesmith',
    postDate: '3h ago',
    postText: 'Check out this amazing video! 🎬',
    postContent: 'https://www.w3schools.com/html/mov_bbb.mp4', // Example video
    messageCount: 5,
    repostCount: 3,
    heartCount: 15,
    viewsCount: 50,
  },
  {
    id: '3',
    profilePic: 'https://i.pravatar.cc/150?img=3',
    fullName: 'Alice Johnson',
    username: 'alicej',
    postDate: '5h ago',
    postText: 'Loving the new UI updates! 💙',
    postContent: 'https://picsum.photos/500/300', // Example random image
    messageCount: 8,
    repostCount: 2,
    heartCount: 25,
    viewsCount: 150,
  },
  {
    id: '4',
    profilePic: 'https://i.pravatar.cc/150?img=4',
    fullName: 'Mike Brown',
    username: 'mikeb',
    postDate: '1d ago',
    postText: 'Throwback to my last trip! 🌍',
    postContent: 'https://placebear.com/500/300', // Example random image
    messageCount: 12,
    repostCount: 7,
    heartCount: 30,
    viewsCount: 200,
  },
  {
    id: '5',
    profilePic: 'https://i.pravatar.cc/150?img=5',
    fullName: 'Emily White',
    username: 'emilyw',
    postDate: '2d ago',
    postText: 'My dog is the cutest! 🐶',
    postContent: 'https://placedog.net/500/300', // Example random image
    messageCount: 20,
    repostCount: 9,
    heartCount: 50,
    viewsCount: 400,
  },
  {
    id: '6',
    profilePic: 'https://i.pravatar.cc/150?img=6',
    fullName: 'David Green',
    username: 'davidg',
    postDate: '3d ago',
    postText: 'A must-watch movie! 🍿',
    postContent: 'https://www.w3schools.com/html/movie.mp4', // Example video
    messageCount: 3,
    repostCount: 1,
    heartCount: 10,
    viewsCount: 30,
  },
  {
    id: '7',
    profilePic: 'https://i.pravatar.cc/150?img=7',
    fullName: 'Sophia Martinez',
    username: 'sophiam',
    postDate: '4d ago',
    postText: 'New coding challenge solved! 💻🔥',
    postContent: 'https://placekitten.com/600/400', // Example random image
    messageCount: 15,
    repostCount: 5,
    heartCount: 35,
    viewsCount: 250,
  },
];
